### ISSUE TITLE
Object Detection with ResNet for Searching

### ISSUE THREAD

**Issue by Dan6erbond** [Dan6erbond/share-me#17]
Implement optional object detection for Share Me that allows users to search for images by tags. This can be leveraged by the MeiliSearch integration added by #16.

## Tasks

- [x] Create Python Service / Find Existing for Object Detection with Docker Container
- [x] Implement Model Hooks to Run Object Detection for Images and Add Detected Objects to Files
- [x] Sync Detected Objects with MeiliSearch

**Comment by Dan6erbond** [comment]
Closed by #24.
