### ISSUE TITLE
API Keys & ShareX Integration

### ISSUE THREAD

**Issue by Dan6erbond** [Dan6erbond/share-me#26]
With popular demand for this feature, ShareX support will require some additional API functionality since PocketBase uses limited duration JWTs for authentication.

This will also allow users to create and manage API keys, with variable expiration.

## Tasks

- [x] Add database table to store hashed keys with `revoked` field.
- [x] Implement API endpoint to generate keys.
- [x] Implement API endpoint to revoke keys.
- [x] Implement API endpoint to create a post with file upload support for ShareX.

**Comment by Dan6erbond** [comment]
Closed by #27.
